stages:
- name: compile
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: tictactest
- name: run
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
notification: {}
