apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticta 
  labels:
    app: tictactest
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tictactest
  template:
    metadata:
      labels:
        app: tictactest
    spec:
      containers:
      - name: tictactest
        image: tictactest
        ports:
        - containerPort: 80
