# This file wont do us much good in this location, make sure you change  
name: Docker CD

on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: npm install and build webpack
        run: |
          npm install
          npm run build
      - uses: actions/upload-artifact@master
        with:
          name: webpack artifacts
          path: public/
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        os: [ubuntu-lastest, windows-2016]
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - uses: actions/download-artifact@master
        with:
          name: webpack artifacts
          path: public
      - name: npm install, and test
        run: |
          npm install
          npm test
        env:
          CI: true
  Build-and-Push-Docker-Image:
    runs-on: ubuntu-latest
    needs: test
    name: Docker Build, Tag, Push
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download built artifact
      uses: actions/download-artifact@master
      with:
        name: webpack artifacts
        path: public
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}
        registry: docker.pkg.github.com
        repository: franz-efang/github-actions-for-packages/tic-tac-toe
        tag_with_sha: true
        tags: latest
    - name: curl
      uses: wei/curl@v1
      with:
        args: -u "token-7lx98:54vfwn9lg8cs57bbd76tm8bgfx52xht7r4ddd5qwsv762qmqx6cbt6" -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' 'https://rancher.abicrash.com/v3/project/c-h9b9n:p-s578s/workloads/deployment:default:tictactest?action=redeploy'
